/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author raulm
 */

import java.util.Random;

import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {
    int i = 0;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        novo = new javax.swing.JButton();
        jogar = new javax.swing.JButton();
        facil = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        numero1 = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        dificil = new javax.swing.JRadioButton();
        titulo = new javax.swing.JLabel();
        nmr1 = new javax.swing.JLabel();
        nmr2 = new javax.swing.JLabel();
        dificuldade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        novo.setText("Criar");
        novo.setEnabled(false);
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        jogar.setText("Jogar");
        jogar.setEnabled(false);
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });

        grupo.add(facil);
        facil.setText("Fácil");
        facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilActionPerformed(evt);
            }
        });

        grupo.add(medio);
        medio.setText("Médio");
        medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioActionPerformed(evt);
            }
        });

        numero1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numero1.setEnabled(false);
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        numero2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numero2.setEnabled(false);
        numero2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                numero2InputMethodTextChanged(evt);
            }
        });
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });
        numero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero2KeyTyped(evt);
            }
        });

        grupo.add(dificil);
        dificil.setText("Difícil");
        dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificilActionPerformed(evt);
            }
        });

        titulo.setText("Jogo");

        nmr1.setText("Número 1:");

        nmr2.setText("Número 2:");

        dificuldade.setText("Dificuldade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nmr1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titulo)
                                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(novo)
                        .addGap(18, 18, 18)
                        .addComponent(jogar)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dificuldade)
                            .addComponent(dificil)
                            .addComponent(facil)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nmr2)
                                .addGap(18, 18, 18)
                                .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmr1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmr2)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(dificuldade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificil)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jogar)
                    .addComponent(novo))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_numero2ActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero1ActionPerformed

    private void facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilActionPerformed
        // TODO add your handling code here:
        novo.setEnabled(true);
        JOptionPane.showMessageDialog(rootPane, "Digite dois numeros de 1 a 10");
        int f = 1;
    }//GEN-LAST:event_facilActionPerformed

    private void medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioActionPerformed
        // TODO add your handling code here:
        novo.setEnabled(true);
        JOptionPane.showMessageDialog(rootPane, "Digite dois numeros de 10 a 100");
        int m = 1;
    }//GEN-LAST:event_medioActionPerformed

    private void dificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificilActionPerformed
        // TODO add your handling code here:
        novo.setEnabled(true);
        JOptionPane.showMessageDialog(rootPane, "Digite dois numeros de 1 a 100");
        int d = 1;
    }//GEN-LAST:event_dificilActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        numero1.setEnabled(true);
        numero2.setEnabled(true);
    }//GEN-LAST:event_novoActionPerformed

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        // TODO add your handling code here:
        int x, y, a, b;
        
        if(facil.isSelected()){
            x = (int)(Math.random() * 10 + 1); 
            y = (int)(Math.random() * 10 + 1);
            
            if(x == Integer.parseInt(numero1.getText())){
                if(y == Integer.parseInt(numero2.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Você Acertou!!");
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Você Errou!");
                    i = i+1;
                }   
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você Errou!");
                i = i+1;
            }
            
            if(i == 2){
            JOptionPane.showMessageDialog(rootPane,"Suas tentativas acabaram");
            
            numero1.setText("");
            numero2.setText("");
            numero1.setEnabled(false);
            numero2.setEnabled(false);
            jogar.setEnabled(false);
            grupo.clearSelection();
            
            i = 0;
            } 
        }
        
        
        if(medio.isSelected()){
            x = (int)(Math.random() * 100 + 10); 
            y = (int)(Math.random() * 100 + 10);
            
            if(x == Integer.parseInt(numero1.getText())){
                if(y == Integer.parseInt(numero2.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Você Acertou!!");
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Você Errou!");
                    i = i+1;
                }   
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você Errou!");
                i = i+1;
            }
            
            if(i == 2){
            JOptionPane.showMessageDialog(rootPane,"Suas tentativas acabaram");

            numero1.setText("");
            numero2.setText("");
            numero1.setEnabled(false);
            numero2.setEnabled(false);
            jogar.setEnabled(false);
            grupo.clearSelection();
            
            i = 0;
            }
        }
        
        if(dificil.isSelected()){
            x = (int)(Math.random() * 100 + 1); 
            y = (int)(Math.random() * 100 + 1);
            
            if(x == Integer.parseInt(numero1.getText())){
                if(y == Integer.parseInt(numero2.getText())){
                    JOptionPane.showMessageDialog(rootPane, "Você Acertou!!");
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Você Errou!");
                    i = i+1;
                }   
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você Errou!");
                i = i+1;
            }
            
            if(i == 2){
            JOptionPane.showMessageDialog(rootPane,"Suas tentativas acabaram");

            numero1.setText("");
            numero2.setText("");
            numero1.setEnabled(false);
            numero2.setEnabled(false);
            jogar.setEnabled(false);
            grupo.clearSelection();
            
            i = 0;
            }
        }
        
        
    }//GEN-LAST:event_jogarActionPerformed

    private void numero2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_numero2InputMethodTextChanged
        // TODO add your handling code here:      
    }//GEN-LAST:event_numero2InputMethodTextChanged

    private void numero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero2KeyTyped
        // TODO add your handling code here:
        jogar.setEnabled(true);
    }//GEN-LAST:event_numero2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton dificil;
    private javax.swing.JLabel dificuldade;
    private javax.swing.JRadioButton facil;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jogar;
    private javax.swing.JRadioButton medio;
    private javax.swing.JLabel nmr1;
    private javax.swing.JLabel nmr2;
    private javax.swing.JButton novo;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
